algolia/vue-instantsearch

- docs/SUMMARY.md
- docs/multi-index-search.md
Closes: #136 
cc @julienbourdeau
> docs(multi-index): add a guide about multi-index search

- book.json
> docs: add edit in GitHub link

- .github/ISSUE_TEMPLATE.md
> chore: add github issue template

- docs/custom-components.md
Just lightly fixing the copy here and there!
> doc(Custom Components): typos

- src/components/RefinementList.vue
The refinement list item class is repeated when the facet value is refined
> fix(RefinementList): repeated item class

- docs/search-store.md
Wrong setter name to change the index on the search store
> doc(SearchStore): fix `index` to `indexName`

- src/components/RefinementList.vue
Reverts algolia/vue-instantsearch#163
as suggested by @rayrutjes 
A live demo with components on every PR like we have on RIS would be really nice here
> Revert "fix(RefinementList): repeated item class"

- docs/SUMMARY.md
- docs/components/input.md
- docs/using-components.md
> docs(input): bootstrap Input component docs

- docs/components/search-box.md
- src/components/SearchBox.vue
- src/components/__tests__/__snapshots__/search-box.js.snap
- src/components/__tests__/search-box.js
I also explicitly passed down the search store to the other components to ease testing.
> Add autofocus capabilities to SearchBox component

- package.json
- src/store.js
- yarn.lock
> fix(store): reject wait sync if error occurs

- docs/docgen/layouts/common/hero.pug
- docs/docgen/layouts/index.pug
- docs/docgen/src/data/communityHeader.json
> docs: replace getting started links

- src/components/Rating.vue
This issue was introduced by #155
> fix(rating): correct star counts

- src/component.js
- src/components/Index.vue
- src/components/PoweredBy.vue
> fix(component): avoid raising injection failure warning

- src/components/Pagination.vue
- src/components/Rating.vue
- src/components/RefinementList.vue
- src/components/Results.vue
- src/components/ResultsPerPageSelector.vue
By using [Vetur](https://github.com/vuejs/vetur), this was very easy to fix.
I think it's safe to close #168 for now.
> feat: add keys to all for loops

- docs/docgen/src/components/tree-menu.md
> docs(tree-menu): bootstrap tree menu docs

- docs/docgen/src/advanced/multi-index-search.md
- docs/docgen/src/getting-started/getting-started.md
- docs/docgen/src/getting-started/search-store.md
- src/__tests__/sanitize-results.js
- src/__tests__/store.js
- src/helper-serializer.js
- src/store.js
I did change `unserialize` to `deserialize`, so it's not only comments and text that changed, but it's not a public method, so it should be okay.
> fix(spelling): run most code through a spell checker

- src/components/RefinementList.vue
- src/components/__tests__/__snapshots__/refinement-list.js.snap
- src/components/__tests__/refinement-list.js
I added to be closer to the original InstantSearch.
> Add BEM classes to some RefinementList tags

- src/components/Pagination.vue
- src/components/Rating.vue
- src/components/RefinementList.vue
- src/components/Results.vue
- src/components/ResultsPerPageSelector.vue
- src/components/SortBySelector.vue
cf https://vuejs.org/v2/api/#key
> fix: use unique keys in all v-for loops

- docs/docgen/src/components/index.md
- src/__tests__/store.js
- src/components/Index.vue
- src/store.js
> feat(store): add methods to interact with cache

- docs/docgen/src/advanced/integrate-with-nuxt.md
> docs(integrate-with-nuxt): add a guide to integrate with Nuxt.js

- src/components/RefinementList.vue
- src/components/__tests__/__snapshots__/refinement-list.js.snap
> fix(refinement-list): remove duplicated class

- docs/docgen/src/components/results.md
> docs(results): add snippet for displaying results in a table

- docs/docgen/src/components/clear.md
- docs/docgen/src/components/highlight.md
- docs/docgen/src/components/index.md
- docs/docgen/src/components/input.md
- docs/docgen/src/components/no-results.md
- docs/docgen/src/components/pagination.md
- docs/docgen/src/components/powered-by.md
- docs/docgen/src/components/price-range.md
- docs/docgen/src/components/rating.md
- docs/docgen/src/components/refinement-list.md
- docs/docgen/src/components/results-per-page-selector.md
- docs/docgen/src/components/results.md
- docs/docgen/src/components/search-box.md
- docs/docgen/src/components/snippet.md
- docs/docgen/src/components/sort-by-selector.md
- docs/docgen/src/components/stats.md
- docs/docgen/src/components/tree-menu.md
This fixes #262
(to be checked in the deploy preview)
> docs(CSS): document css classes in code tag

- docs/src/getting-started/styling.md
> docs(styling): add styling guide

- docs/src/components/highlight.md
Added an example for using _highlightResult for more complex use cases.
> [docs] update highlight.md

- src/components/Stats.vue
Thoughts on updating stats component to format numbers using toLocaleString() as opposed to leaving numbers entirely unformatted?
> Update stats component to use toLocaleString()

- CHANGELOG.md
- package.json
cc @ehayman should be available in the next minutes.
> chore(release): v1.2.0

- .storybook/config.js
- .storybook/styles.css
- docs/package.json
- docs/src/components/clear.md
- docs/src/components/no-results.md
- docs/src/components/pagination.md
- docs/src/components/powered-by.md
- docs/src/components/refinement-list.md
- docs/src/components/results-per-page-selector.md
- docs/src/components/search-box.md
- docs/src/components/sort-by-selector.md
- docs/src/components/stats.md
- docs/src/components/tree-menu.md
- docs/src/getting-started/using-components.md
- docs/src/stylesheets/components/_buttons.sass
- package.json
- src/components/Results.vue
- src/components/__tests__/pagination.js
- stories/Clear.stories.js
- stories/NoResults.stories.js
- stories/Pagination.stories.js
- stories/PoweredBy.stories.js
- stories/RefinementList.stories.js
- stories/ResultsPerPageSelector.stories.js
- stories/SearchBox.stories.js
- stories/SortBySelector.stories.js
- stories/Stats.stories.js
- stories/TreeMenu.stories.js
- stories/utils.js
- yarn.lock
https://59e661aca6188f358de1cf25--vue-instantsearch.netlify.com/stories/
cc @mthuret @iam4x @samouss
> 🕹 Feat/add stories

- CHANGELOG.md
- package.json
Special thx to @iam4x & @samouss 🎉
> chore(release): v1.3.0

- src/components/Clear.vue
- src/components/Index.vue
- src/components/Input.vue
- src/components/Menu.vue
- src/components/NoResults.vue
- src/components/Pagination.vue
- src/components/PoweredBy.vue
- src/components/PriceRange.vue
- src/components/Rating.vue
- src/components/RefinementList.vue
- src/components/Results.vue
- src/components/ResultsPerPageSelector.vue
- src/components/SearchBox.vue
- src/components/SortBySelector.vue
- src/components/Stats.vue
- src/components/TreeMenu.vue
newer version of Vetur indents it correctly, so I saved all files :fire:
> chore(components): put import on newline

- src/components/PoweredBy.vue
Add a null check to the `location` reference in `algoliaUrl`.
fixes #367
> fix: Powered-by component is not SSR compatible #367

- src/components/RefinementList.vue
this should fix https://github.com/algolia/vue-instantsearch/issues/381
> fix(refinementList): avoid unwanted spacing

- CHANGELOG.md
- package.json
> chore(release): v1.5.1

- src/components/RangeInput.vue
> fix(RangeInput): also update footer slot

- bin/release-branch.sh
This is part of `hub`, which I use :joy:
> chore(release): also try `git browse`

- docs/src/components/stats.md
per https://github.com/algolia/vue-instantsearch/pull/449
> doc(Stats): give complete info in demo

- docs/src/components/stats.md
- src/components/Stats.vue
- src/components/__tests__/stats.js
see #449 and #450 for detailed info
>  feat(Stats): add more info to slot

- docs/src/advanced/custom-backend.md
This is the same content as algolia/instantsearch.js#2943 with Vue code samples in "Using the search client with InstantSearch".
[:link: **Link to the guide**](https://deploy-preview-459--vue-instantsearch.netlify.com/advanced/custom-backend.html)
> docs(guide): Add Custom Backend guide

- .github/V2_PROGRESS.md
- .storybook/styles.css
- docs/src/components/ToggleRefinement.md
- src/__tests__/index.js
- src/components/ToggleRefinement.vue
- src/components/__tests__/ToggleRefinement.js
- src/components/__tests__/__snapshots__/ToggleRefinement.js.snap
- src/instantsearch.js
- stories/ToggleRefinement.stories.js
- stories/utils.js
**Summary**
This PR implements the `ToggleRefinement` widget.
You can try the widget on [Storybook]().
> feat(ToggleRefinement): implement widget

- docs/src/components/current-refinements.md
- src/components/CurrentRefinements.vue
- src/components/__tests__/__snapshots__/current-refinements.js.snap
- src/components/__tests__/current-refinements.js
- stories/CurrentRefinements.stories.js
> feat(CurrentRefinements): add the current refinements widget

- docs/src/components/index.md
- src/__tests__/component.js
- src/component.js
- src/components/Index.vue
- src/components/__tests__/Index.js
- src/components/__tests__/__snapshots__/Index.js.snap
- stories/utils.js
This PR updates the Index component so that it supports the same set of options as instantSearch(). It also removes the deprecated apiKey / appId parameters.
I don't know what would be a good strategy for testing the Index. Happy to pair with someone to figure out what would be a good approach.
> fix(Index): missing parameters / props

- docs/src/advanced/vue-router-url-sync.md
- stories/Menu.stories.js
- stories/NoResults.stories.js
- stories/RefinementList.stories.js
- stories/SortBySelector.stories.js
- stories/TreeMenu.stories.js
- stories/utils.js
> fix(docs): remove Ikea index usage

- docs/src/advanced/integrate-with-nuxt.md
- docs/src/advanced/multi-index-search.md
- docs/src/advanced/server-side-rendering.md
- docs/src/advanced/vue-router-url-sync.md
- docs/src/getting-started/custom-components.md
- docs/src/getting-started/getting-started.md
- docs/src/getting-started/installing.md.hbs
- docs/src/getting-started/migration.md
- docs/src/getting-started/styling.md
- docs/src/getting-started/using-components.md
>  docs: migration guide

- examples/ecommerce/src/App.css
- examples/ecommerce/src/App.vue
> chore(ecommerce): add style for no results

- package.json
- src/components/Configure.js
- src/components/__tests__/__snapshots__/Configure.js.snap
see https://vuejs.org/v2/api/#inheritAttrs for more info. This version is from July 2017, so more than old enough for us
> feat(Configure): don't add attributes to the DOM

- docs/src/advanced/custom-components.md
Also mention the regular way first, with the slots
> docs: rewrite custom components guide

- docs/src/components/MenuSelect.md
- src/components/MenuSelect.vue
- src/components/__tests__/MenuSelect.js
- src/components/__tests__/__snapshots__/MenuSelect.js.snap
- stories/MenuSelect.stories.js
test is not doing `template` because of https://github.com/vuejs/vue-test-utils/pull/507
> feat(MenuSelect): add item slot

- examples/default-theme/sandbox.config.json
- examples/ecommerce/sandbox.config.json
- examples/media/sandbox.config.json
see https://github.com/CompuIves/codesandbox-client/issues/1179#issuecomment-432305547
working urls: 
* https://codesandbox.io/s/github/algolia/vue-instantsearch/tree/fix/codesandbox-examples/examples/default-theme
* https://codesandbox.io/s/github/algolia/vue-instantsearch/tree/fix/codesandbox-examples/examples/ecommerce
https://codesandbox.io/s/github/algolia/vue-instantsearch/tree/fix/codesandbox-examples/examples/media
> fix(example): add codesandbox config

- docs/src/components/RangeInput.md
- src/components/RangeInput.vue
- stories/RangeInput.stories.js
1. currentRefinements -> currentRefinement
2. currentRefinement: object
3. refine: object
The tests aren't changed; since the internal refine is tested, not the exposed one
IFW-196
> feat(RangeInput): refine & currentRefinement sync

- docs/src/components/RefinementList.md
- src/components/RefinementList.vue
- src/components/__tests__/RefinementList.js
- src/components/__tests__/__snapshots__/RefinementList.js.snap
Also noticed that the test was broken for `searchable`, so fixed that one too.
New prop: `searchable-placeholder` on `ais-refinement-list`
fixes #572
> fix(RefinementList): allow overriding of searchable placeholder

- docs/src/advanced/custom-components.md
> docs(custom): expose refine on the slots

- examples/nuxt/nuxt.config.js
- examples/nuxt/package.json
- examples/nuxt/pages/search.vue
- examples/nuxt/yarn.lock
- examples/ssr/package.json
- examples/ssr/src/main.js
- examples/ssr/src/views/Search.vue
- examples/ssr/vue.config.js
- examples/ssr/yarn.lock
Still to do: make Nuxt work with nodeExternalsWhitelist
> chore(examples): use published version of Vue InstantSearch

- CHANGELOG.md
- package.json
fixes UMD "in page" usage, so quite important to fix (two people have noticed)
> chore(release): v2.0.1

- package.json
- stories/RangeInput.stories.js
- yarn.lock
fixes #647 (the other fix is in the doc repo: https://github.com/algolia/doc/pull/2818)
> fix(stories): update range slider component to v3

- package.json
- yarn.lock
**Summary**
Update `instantsearch.js` dependency from `v3.1.1` to `v3.4.0`
[Changelog](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#340-2019-04-17)
Saldy it also makes the UMD bundle bigger due to the new features in `instantsearch.js`.
**Result**
No visible changes.
> chore(deps): update dependency instantsearch.js to v3.4.0

- package.json
- src/components/QueryRuleContext.js
- src/components/QueryRuleCustomData.vue
- src/components/__tests__/QueryRuleContext.js
- src/components/__tests__/QueryRuleCustomData.js
- src/widgets.js
- stories/QueryRuleContext.stories.js
- stories/QueryRuleCustomData.stories.js
- yarn.lock
> feat(query-rules): add new widgets

- CHANGELOG.md
- package.json
- query rules
- infinite hits
- insights
- label for toggle-refinement
> chore(release): v2.1.0

- src/components/Highlight.vue
- src/components/__tests__/Highlight.js
- src/components/__tests__/RefinementList.js
fixes #639 
to fully fix #639, we also want algolia/instantsearch.js#3830 to be merged, however those are completely separate issues
> fix(highlight): change expected tag to replace

- examples/ecommerce/src/App.css
This adds style to app.css to wrap words.
Propagated from https://github.com/algolia/instantsearch.js/pull/3913
> chore(examples): add app style for word wrap in e-commerce demo

- package.json
- yarn.lock
fixes #663
Confirmed this in: https://codesandbox.io/s/check-extra-request-higuj (you need to clone it, CodeSandbox doesn't deduplicate the dependency as expected)
> fix(core): prevent duplicating facet values

- src/components/SearchBox.vue
- src/components/SearchInput.vue
At Netlify we needed these events to make changes to the rest of the site.
> feat: Adds events to hook on to focus, blur, and reset

- CHANGELOG.md
- package.json
> chore(release): v2.4.0

- CHANGELOG.md
- package.json
> chore(release): v2.5.0

- src/components/Snippet.vue
- src/components/__tests__/Snippet.js
> fix(Snippet): switch tag replacement to mark

- .circleci/config.yml
- examples/build.sh
- examples/e-commerce/src/App.vue
- changed examples script to allow building a single example
- actually build & move folders for e-commerce demo
- fix a small error in slider in the example
> chore(ci): fix e2e tests

- package.json
- src/util/createServerRootMixin.js
- yarn.lock
uses https://github.com/algolia/instantsearch.js/pull/4603 & https://github.com/algolia/instantsearch.js/pull/4609
> refactor(ssr): reuse index helpers

- src/util/createServerRootMixin.js
related to #936, this would allow people to link items to the cloned component themselves
> feat(ssr): expose clone component

- .circleci/config.yml
- scripts/test-vue3.sh
This PR extracts the commands run in CircleCI as a script file to run tests with vue 3.
> chore(vue 3): extract commands as a file to run tests with vue 3

- stories/Breadcrumb.stories.js
- stories/ClearRefinements.stories.js
- stories/DynamicWidgets.stories.js
- stories/HierarchicalMenu.stories.js
- stories/Hits.stories.js
- stories/HitsPerPage.stories.js
- stories/InfiniteHits.stories.js
- stories/Menu.stories.js
- stories/MenuSelect.stories.js
- stories/NumericMenu.stories.js
- stories/Pagination.stories.js
- stories/Panel.stories.js
- stories/RangeInput.stories.js
- stories/RatingMenu.stories.js
- stories/SearchBox.stories.js
- stories/SortBy.stories.js
- stories/Stats.stories.js
- stories/ToggleRefinement.stories.js
- stories/VoiceSearch.stories.js
already updated in the components themselves
> chore(vue): update to newer slot format in stories

- src/components/DynamicWidgets.js
- src/components/ExperimentalDynamicWidgets.js
- src/widgets.js
- stories/DynamicWidgets.stories.js
> feat(dynamicWidgets): release as production

- src/components/__tests__/ExperimentalDynamicWidgets.js
forgotten to commit this in #1086
> test(experimental-dynamic-widgets): commit the tests

- package.json
- src/mixins/widget.js
- src/util/__tests__/createServerRootMixin.test.js
- src/util/createServerRootMixin.js
- src/util/testutils/helper.js
- yarn.lock
Same as #1090, but for Vue InstantSearch v3
fixes algolia/vue-instantsearch#1066
fixes algolia/vue-instantsearch#1062
closes https://github.com/algolia/instantsearch.js/pull/5002
> feat(ssr): prevent initial network request

- package.json
- yarn.lock
**Summary**
This PR updates `instantsearch-e2e-tests` to its latest version.
**Result**
Pipelines should have less issues with flaky tests.
> chore: update e2e tests

- src/components/Pagination.vue
- src/components/__tests__/__snapshots__/Pagination.js.snap
https://github.com/algolia/vue-instantsearch/issues/1128
> add page class for "page" item

- src/components/InstantSearch.js
- src/util/createInstantSearchComponent.js
> feat(InstantSearch): support onStateChange
