algolia/vue-instantsearch

docs/components/pagination.md, src/components/Pagination.vue, src/components/__tests__/__snapshots__/pagination.js.snap, src/components/__tests__/pagination.js
Makes sure pagination never goes below 1.
Also hides the pagination component if there are not search results in the current context. Thanks @olance for spotting that weird behaviour 👍 
fixes #182
=> Ensure page never drops below 1 in pagination component

src/store.js
This solves the following scenario:
**Issue solved:**
1. create a new store
2. start it and get the first results
3. dynamically register a facet
4. component will try to getFacetValues out of the previous results that do not have facet values yet
**Solution:**
We catch the exception when trying to get the facet values out of the helper.lastResults.
Closes: #184 
cc @olance
=> fix(store): catch errors on facet values retrieval

docs/docgen/src/components/pagination.md, docs/docgen/syntaxHighlighting.js, src/components/Pagination.vue, src/components/__tests__/pagination.js
allows to listen for page change and to act upon it for example for scrolling to the top of the page.
Closes: #231
**WIP:**
=> feat(pagination): emit pageChanged event

docs/docgen/syntaxHighlighting.js
AFAIK, these languages aren’t used, unless I misunderstood something. Let’s check it in the deploy preview
=> docs(highlighting): remove unused languages

src/components/Index.vue
The first ones do not apply anymore, because we re-worked the error message in the component mixin.
The other one does not apply because if store is provided by parent, then we do nothing.
=> style(index): remove todos that no longer apply

docs/docgen/src/components/index.md, docs/docgen/src/getting-started/custom-components.md, docs/docgen/src/getting-started/search-store.md, src/__tests__/store.js, src/components/Clear.vue, src/components/Index.vue, src/components/Input.vue, src/components/PriceRange.vue, src/components/Rating.vue, src/components/RefinementList.vue, src/components/Results.vue, src/components/ResultsPerPageSelector.vue, src/components/SortBySelector.vue, src/components/TreeMenu.vue, src/components/__tests__/__snapshots__/sort-by-selector.js.snap, src/components/__tests__/clear.js, src/components/__tests__/menu-tree.js, src/components/__tests__/refinement-list.js, src/components/__tests__/sort-by-selector.js, src/store.js
This PR removes all usage of the `$mounted` lifecycle hook.
Only `created` and `beforeCreated` are used on the server side.
Remaining `destroyed` and `mounted` still makes sense (unless I forgot some).
=> Make all components SSR ready

build/rollup.umd.config.js, src/instantsearch.js, src/instantsearch.umd.js
This PR makes sure that users using the ES module can tree shake unused code.
This PR removes the auto-registration of the Vue-InstantSearch plugin inside Vue in all builds but UMD.
Closes: #311
=> fix(instantsearch): allow to treeshake es module

docs/src/getting-started/styling.md
As define in doc: https://vuejs.org/v2/api/#extends
Otherwise in raise: **Property or method "results" is not defined on the instance but referenced during render**
=> Fix typo on `extend` instruction

docs/src/components/rating.md
Hello,
The Rating component is waiting for a literal string therefore current examples are not working.
=> Update Rating documentation examples

docs/src/components/range-input.md, docs/src/getting-started/using-components.md, jest.setup.js, package.json, src/__tests__/index.js, src/__tests__/store.js, src/components/RangeInput.vue, src/components/__tests__/__snapshots__/range-input.js.snap, src/components/__tests__/range-input.js, src/instantsearch.js, src/store.js, stories/RangeInput.stories.js
**Summary:**
Addition of the `RangeInput` widget, following the behaviour of InstantSearch & React InstantSearch.
**Result:**
You can play with the `RangeInput` on [Storybook](https://deploy-preview-344--vue-instantsearch.netlify.com/stories/?selectedKind=RangeInput&selectedStory=default&full=0&down=1&left=1&panelRight=0).
=> Feature: RangeInput widget

docs/src/components/menu.md, src/components/Menu.vue, src/components/__tests__/menu.js, stories/Menu.stories.js
This PR shows that the "limit" is not respected.
https://deploy-preview-341--vue-instantsearch.netlify.com/stories/?selectedKind=Menu&selectedStory=limit%20the%20facet%20values&full=0&down=1&left=1&panelRight=0
cc @iam4x
=> chore(stories): add Menu component stories

docs/src/advanced/integrate-with-nuxt.md, docs/src/components/highlight.md, docs/src/components/no-results.md, docs/src/components/results.md, docs/src/components/sort-by-selector.md, docs/src/components/stats.md, docs/src/getting-started/getting-started.md, docs/src/getting-started/styling.md
The "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since Vue 2.5.
=> Update scoped slot docs

src/components/Menu.vue, src/components/RangeInput.vue, src/components/Rating.vue, src/components/RefinementList.vue, src/components/TreeMenu.vue, src/components/__tests__/menu-tree.js, src/components/__tests__/refinement-list.js
=> fix: avoid query when components are destroyed

docs/src/components/index.md
1. cache: make into a shortened link
2. api parameters: use the correct link, cc @kfirba
=> docs(index): correct documentation links

docs/src/getting-started/search-store.md
`queryParameters` actually has a setter that merges assigned params to the full params list
=> fix(doc): `queryParameters` is not a function

src/components/Results.vue, stories/Results.stories.js
This reveals the relative hit position, and is needed for example for analytics
=> feat(Results): add `index` (position)

docs/src/components/index.md, src/__tests__/store.js, src/components/Index.vue, src/components/SearchBox.vue, src/components/__tests__/__snapshots__/search-box.js.snap, src/components/__tests__/search-box.js, src/store.js, stories/SearchBox.stories.js
This PR provides a way for the searchbox to display a spinner when the search is stalled.
The approach taken here is [similar to the one from react-instantsearch](https://github.com/algolia/react-instantsearch/pull/544): the mechanism that detects the stalled search is actually implemented at the top level. As in RIS this makes the implementation of this state update easier in multiple widgets, which seems like a good strategy.
On the UI implementation, because vue-IS doesn't implement any style, the magnifying glass svg is toggle with a spinner in the template. The effect is good as far as I can tell.
Missing elements:
Question: 
- not sure about the implementation in store.js/waitUntilSync @rayrutjes 
Related to https://github.com/algolia/instantsearch.js/pull/2509
=> feat: provide a loading indicator

src/components/Highlight.js, src/util/warn.js
=> fix(Highlight): only warn once for possibly missing highlighting

docs/src/advanced/integrate-with-nuxt.md
This was reported by a user having followed the steps properly.
The `start` method used to call `search()` on the helper at some point, then we isolated that in a `refresh` method for more control.
=> docs(integrate-with-nuxt): add missing method call

src/components/Menu.vue, src/components/__tests__/__snapshots__/menu.js.snap, src/components/__tests__/menu.js
Works around a bug in the Menu component implementation:
cc @Shipow
=> fix(menu): avoid error when no facet values are retrieved

src/__tests__/store.js, src/store.js
cc @ehayman 
I'm wondering if we should always return an empty array in case no data is available or if we should leave this check up to the user.
=> feat(store): expose userData through a new getter

src/components/RangeInput.vue
=> fix(RangeInput): make the header slot valid

package.json, yarn.lock
This PR makes the testing watch mode work.
* In Jest 20, errors are thrown when running `jest --watch`.
* In Jest 22, tests break.
=> chore: Upgrade to Jest 21

package.json, yarn.lock
Upgrades JS helper to `2.26.0` which makes clients `addAlgoliaAgent()` and `clearCache()` optional.
=> chore: Upgrade Helper 2.26.0

docs/src/components/index.md, docs/src/getting-started/search-store.md, src/components/Index.vue, src/components/__tests__/__snapshots__/index.js.snap, src/components/__tests__/index.js, src/store.js
_This PR adds supports for the `search-client` prop. This allows any InstantSearch user to plug his own search client (including a custom Algolia backend)._
```html
<template>
<ais-index
index-name="instant_search"
:searchClient="searchClient"
>
...
</ais-index>
</template>
<script>
import algoliasearch from "algoliasearch";
export default {
data() {
return {
searchClient: algoliasearch("latency", "6be0576ff61c053d5f9a3225e2a90f76")
};
}
};
</script>
```
[![View Demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vv7wr6p4q7)
(see file `src/App.vue`)
> algolia/instantsearch.js#2894
=> feat(search-client): Add support for Custom Search Clients

src/components/NoResults.vue
This comp misfires a lot when loading legit results (flashes on/off), just watch searchStore.results.length to find out.  This tweak at least makes it so it will only show when you actually launched a query.
=> Stop false positives in No Results Comp!

src/components/Stats.vue
Adding resultStart and resultEnd gives you "Amazon Like" stats.  For example "Showing {{ resultStart }} - {{ resultEnd }} of {{ totalResults }}" would show "Showing 31 - 60 of 123" when you are on page 2 with 30 / page.
Adding just these 2 things makes this comp much more usable in production.
=> feat(Stats): add more info to slot

src/components/SearchBox.vue, src/components/__tests__/__snapshots__/search-box.js.snap
We never noticed it because this wasn't a very popular API, but if you use vanilla ais-search-box, you can not override the class names of the input or the clear which are nested within the component.
This is not an issue we have in v2, since we removed this API and no longer nest components in eachother, so it doesn't need to be passed around.
Using the `:class-names` API to pretend v1 is using InstantSearch.css with @francoischalifour made me realise that this is a useful API to keep, so it should be replicated in v2 as well.
(this change was tested in @francoischalifour's node_modules)
=> fix(SearchBox): propagate the classname overrides to children

docs/src/components/pagination.md
in v2 this is `item` instead of `value`
fixes #464
=> docs(pagination): correct provided value to slot

docs/src/components/index.md
The `attributeForDistinct` parameter isn't a search parameter, so it can't be used with the `query-parameters` prop.
This follows up on a HelpScout ticket: https://secure.helpscout.net/conversation/617944989/74808?folderId=1106372
=> docs(index): fix parameter used in example

docs/src/components/menu.md, src/components/Menu.vue, src/components/__tests__/__snapshots__/menu.js.snap, src/components/__tests__/menu.js, stories/Menu.stories.js
This PR implements the `Menu` widget.
You can try the widget on [Storybook](https://deploy-preview-478--vue-instantsearch.netlify.com/stories/?selectedKind=Menu&full=0&addons=1&stories=1&panelRight=0).
One thing to note is that I scoped the top level `div` of the widget under the `slot`. It avoids to still have the top level className when you completely rewrite the widget. But it introduce a top level `div` on top of the widget (see picture below). It can be removed when Vue will support a ["Fragment"](https://github.com/vuejs/vue/issues/7088) like component. Do we want to implement this behaviour on all the widgets?
**With default render**
**With custom render**
=> feat(Menu): add widget

.storybook/styles.css, stories/Breadcrumb.stories.js, stories/ClearRefinements.stories.js, stories/Configure.stories.js, stories/CurrentRefinements.stories.js, stories/HierarchicalMenu.stories.js, stories/Hits.stories.js, stories/HitsPerPage.stories.js, stories/InfiniteHits.stories.js, stories/Menu.stories.js, stories/MenuSelect.stories.js, stories/NoResults.stories.js, stories/Pagination.stories.js, stories/PoweredBy.stories.js, stories/RatingMenu.stories.js, stories/RefinementList.stories.js, stories/SearchBox.stories.js, stories/SortBy.stories.js, stories/Stats.stories.js, stories/TreeMenu.stories.js, stories/utils.js
This PR adds some styles to Storybook, it's pretty basic feel free to update it. I took almost the same style as the one implemented in React InstantSearch. As soon as we have the `ClearRefinements` widget we should add it with a two column layout along with a `RefinementList`. It will allow us to play with almost all the widget easily.
**Before**
**After**
You play with the live example on [Storybook](url).
=> chore(Storybook): add styles

.github/V2_PROGRESS.md, docs/src/components/Breadcrumb.md, src/components/Breadcrumb.vue, src/components/__tests__/Breadcrumb.js, src/components/__tests__/__snapshots__/Breadcrumb.js.snap, stories/Breadcrumb.stories.js
**Summary**
This PR implements the `Breadcrumb` widget. Note that the story use the `Configure` widget to test the `Breadcrumb`. We need to change it to the `HierarchicalMenu` once it's implemented.
You can use the widget on [Storybook](https://deploy-preview-493--vue-instantsearch.netlify.com/stories/?selectedKind=Breadcrumb&selectedStory=default&full=0&addons=1&stories=1&panelRight=0).
=> feat(Breadcrumb): implement widget

.github/V2_PROGRESS.md, docs/src/components/HierarchicalMenu.md, package.json, src/components/HierarchicalMenu.vue, src/components/HierarchicalMenuList.vue, src/components/__tests__/HierarchicalMenu.js, src/components/__tests__/__snapshots__/HierarchicalMenu.js.snap, stories/Breadcrumb.stories.js, stories/HierarchicalMenu.stories.js, stories/utils.js, yarn.lock
**Summary**
This PR implements the `HierarchicalMenu` widget. The PR also adds the ability to override the filters section of the preview wrapper from the stories. I've updated the `Breadcrumb` stories to use a `HierarchicalMenu` rather than the `Configure` widget.
I've also updated the Jest plugin that preprocess the Vue files from [Jest Vue Preprocessor](https://github.com/vire/jest-vue-preprocessor) to [Vue Jest](https://github.com/vuejs/vue-jest). The latter has a better support for functional components (it's the official plugin for Jest).
You can use the widget on [Storybook](https://deploy-preview-494--vue-instantsearch.netlify.com/stories/?selectedKind=HierarchicalMenu).
=> feat(HierarchicalMenu): implement widget

src/components/SearchBox.vue, stories/MultiIndex.stories.js
We allow the search box to be controlled via v-model. If you do that, you can sync between multiple search boxes across multiple indices
There's still an issue that this does 2n requests (not sure why, but at least it works). This would be caught by the newer request cache (not enabled by default)
=> feat: allow search box to be controlled -> multi query!

docs/src/data/communityHeader.json
I get a lot of emails from Netlify about this:
Worth checking other *-instantsearch websites for this:
=> docs(https): fix https mixed content

.github/CONTRIBUTING.md, package.json, scripts/get-npm-tag.js, scripts/get-version.js, scripts/release-branch.sh, scripts/release-publish.sh
The flow didn't change, except that now you can give a prerelease-style version and it will release on the right npm tag
=> chore(release): allow prerelease

docs/src/advanced/vue-router-url-sync.md
note i don't use vue router all the time in the guide, but i think that's fine in _most_ use cases
see also #544 for seeing if we need to ship this config in the library or not. So far I haven't found a sufficiently good way of including it, so left it in user land, mostly because of the "flat" or "nested arrays" problem.
=> docs(router): how to use it

.storybook/config.js, .storybook/styles.css, docs/src/components/ClearRefinements.md, docs/src/components/CurrentRefinements.md, src/components/ClearRefinements.vue, src/components/CurrentRefinements.vue, src/components/SearchBox.vue, src/components/__tests__/ClearRefinements.js, src/components/__tests__/CurrentRefinements.js, src/components/__tests__/__snapshots__/CurrentRefinements.js.snap, stories/ClearRefinements.stories.js, stories/CurrentRefinements.stories.js
API of ClearRefinements & CurrentRefinements is consolidated
1. ClearRefinements has no `includedAttributes`. This is waiting for v3 of InstantSearch.js and will be added without breaking change
2. Searchbox: don't display internal value (otherwise you can clear the query but it stays visible)
3. CurrentRefinements: `includedAttributes` transparently takes precedence over `excludedAttributes`. 
If you don't want to display specific attributes listed in `includedAttributes`, don't write them or use `transformItems`. 
This doesn't implement the "merged items" done in InstantSearch.js v3, which will be added later (we can do a major maybe)
=> feat(CurrentRefinements): consolidate API

docs/src/components/CurrentRefinements.md, src/components/CurrentRefinements.vue, src/components/__tests__/CurrentRefinements.js, src/components/__tests__/__snapshots__/CurrentRefinements.js.snap
The function is prefilled this with the item.
I'm doubting if maybe it should be prefilled with the url in the `item` itself instead? This is a larger change and we can do it another time though
=> feat(CurrentRefinements): give createURL to slot

docs/src/advanced/vue-router-url-sync.md, docs/src/components/InstantSearch.md, docs/src/getting-started/migration.md, examples/default-theme/package.json, examples/default-theme/src/App.vue, examples/default-theme/yarn.lock, examples/ecommerce/package.json, examples/ecommerce/src/App.vue, examples/ecommerce/yarn.lock, examples/media/package.json, examples/media/src/App.vue, examples/media/yarn.lock, src/components/InstantSearch.vue, src/components/__tests__/InstantSearch.js
IFW-221
We force the object form, because that way there's less options, using it as a widget would indeed be nicer than as option, but we can do that later, I didn't completely grasp how to do that with InstantSearch.js, it seems to be setting some internal things, more than just a widget
=> feat(router): force object form

docs/src/advanced/conditional-requests.md
This is the most correct way of preventing initial search, both in InstantSearch v1 and v2
fixes no specific open issue, but people have been asking this capability time and time again.
IFW-220
=> docs(SearchClient): preventing (initial & empty) request

stories/RefinementList.stories.js
The searchable RefinementList was not working because the `categories` attribute is not searchable. I've updated all the stories to `brand` (which is searchable) for consistencies accross the stories of this widget.
=> chore(stories): move RefinementList example on brand

.storybook/styles.css, stories/utils.js
Avoid a conflict with the classname of Storybook.
**Before**:
**After**:
=> chore(stories): avoid classnames conflict for container

docs/src/components/RatingMenu.md, src/components/RatingMenu.vue
This isn't a breaking change, since it wasn't functional, but I've mentioned it in the changelog
=> fix(rating-menu): remove nonfunctional min prop

docs/src/components/MenuSelect.md, src/components/MenuSelect.vue, src/components/__tests__/MenuSelect.js, src/components/__tests__/__snapshots__/MenuSelect.js.snap
This is a breaking change, change from `<ais-menu-select :label="all">` to `<ais-menu-select><template slot="defaultOption">all</template></ais-menu-select>`
closes IFW-333
=> feat(MenuSelect): use a slot for "all"

src/components/Breadcrumb.vue, src/components/ClearRefinements.vue, src/components/HierarchicalMenu.vue, src/components/Hits.vue, src/components/HitsPerPage.vue, src/components/InfiniteHits.vue, src/components/Menu.vue, src/components/MenuSelect.vue, src/components/NumericMenu.vue, src/components/Pagination.vue, src/components/RatingMenu.vue, src/components/RefinementList.vue, src/components/SortBy.vue, src/components/Stats.vue, src/components/ToggleRefinement.vue, src/mixins/widget.js
If an inline element has whitespace, and then a text node, Vue will preserve this whitespace inside the component, and thus it will take up bundle size (a tiny little bit)
=> fix(components): remove faulty whitespace

docs/_redirects, docs/package.json
This redirects the Vue InstantSearch Netlify website index page to the Algolia documentation website.
I just copied the Netlify `_redirects` file to the website `dist/` folder during the build process. This should be enough for now since we'll get rid of the docgen website.
=> docs(website): redirect Netlify website to Algolia

docs/layouts/common/meta.pug
This is fine, since v2 docs aren't commonly used and not indexed in Google yet anyway
=> docs(v2): add noindex to docs

docs/layouts/common/meta.pug, docs/package.json, docs/src/_redirects
depends on https://github.com/algolia/doc/pull/2662 to be released first
This doesn't need to be put on gh-pages, since it will be replaced by netlify
=> docs(v1): add redirect to root & noindex to rest

rollup.config.js, src/instantsearch.umd.js, src/plugin.js
This is fixed in two spots:
1. add Vue to externals for the UMD (used in Panel)
2. use the Vue object passed to the install function instead of importing it ourselves (in the plugin)
Furthermore this also fixes the plugin which needlessly exposes all widgets (you can already import them easily, since the default export is being put on the window)
=> fix(umd): prevent inclusion of Vue in bundle

README.md
Updated documentation and contributing links on readme. Still needs to update release tags (maybe on next release) because 2.0.0 tags' readme still shows old versions' documentation links.
Also fixed CONTRIBUTING.md path as .github/CONTRIBUTING.md in readme.
Maybe you can check the complete project for community.algolia.com/vue-instantsearch later. There are someother recors for that url, I didn't change those.
=> docs(readme): update to use correct links of the new docs

src/components/ToggleRefinement.vue, src/components/__tests__/ToggleRefinement.js, src/components/__tests__/__snapshots__/ToggleRefinement.js.snap
The required `label` of the [`ais-toggle-refinement`](https://www.algolia.com/doc/api-reference/widgets/toggle-refinement/vue/) widget was not used in the template, thus ignored. The [deployed story](https://vue-instantsearch.netlify.com/stories/?selectedKind=ais-toggle-refinement&selectedStory=default) should display "Free shipping" but displays the attribute name "free_shipping".
This issue was reported by a user.
=> fix(toggle-refinement): display label

.storybook/addons.js, package.json, src/components/InstantSearch.js, src/components/__tests__/InstantSearch.js, stories/utils.js, yarn.lock
**Summary**
This prepares for the insights stories to be added illustrating the usage of Hits and InfiniteHits widgets with insights.
=> feat(insights): add insightsClient support on storybook

package.json, src/components/InfiniteHits.vue, src/components/__tests__/InfiniteHits.js, src/components/__tests__/__snapshots__/InfiniteHits.js.snap, stories/InfiniteHits.stories.js, stories/MemoryRouter.js, stories/utils.js, yarn.lock
**Summary**
The [InfiniteHits widget](https://www.algolia.com/doc/api-reference/widgets/infinite-hits/vue/) is used to display a list of results with a “Show more” button. The user can click on this button to display more results without leaving its current page context.
Each time the user click on the “Show more” button the user will navigate to a new page (provided that [the routing option is enabled in ais-instant-search](https://www.algolia.com/doc/api-reference/widgets/instantsearch/vue/)).
However, in the case the user navigates directly to a particular page (direct link, previous button, page refresh) then the widget only displays the last result page.
This change add a previous button to the Infinite Hits widget to give the possibility to the user to load the previous result …
=> feat(infiniteHits): add previous button

src/components/Hits.vue, src/components/__tests__/Hits.js, stories/Hits.stories.js
**Summary**
This integrates insights with Vue Instantsearch to help using Click Analytics in Hits.
Using `connectHitsWithInsights` instead of `connectHits` exposed a new property `insights` to the internal state, which user can call to emit insights events.
**Result**
```html
<ais-hits>
<div slot-scope="{ items, insights }">
<div v-for="item in items">
<button @click="insights('clickedObjectIDsAfterSearch', { eventName: 'Add to cart', objectIDs: [item.objectID] })">Add to cart</button>
</div>
</div>
</ais-hits>
```
=> feat(insights): add insights support to Hits widget

package.json, src/components/InfiniteHits.vue, src/components/__tests__/InfiniteHits.js, stories/InfiniteHits.stories.js
⚠️ This PR depends on #664, it can't work until it's merged. It will stay as draft until then.
**Summary**
This integrates insights with Vue Instantsearch to help using Click
Analytics in InfiniteHits.
Using `connectInfiniteHitsWithInsights` instead of `connectInfiniteHits`
exposed a new property `insights` to the internal state, which user can
call to emit insights events.
**Result**
```html
<ais-infinite-hits>
<div slot-scope="{ items, refine, insights }">
<div v-for="item in items">
<button @click="insights('clickedObjectIDsAfterSearch', { eventName: 'Add to cart', objectIDs: [item.objectID] })">Add to cart</button>
</div>
<button @click="refine()"> Load more </button>
</div>
</ais-infinite-hits>
```
=> feat(insights): add insights support to InfiniteHits widget

src/components/Panel.vue, src/components/__tests__/Panel.js
This allows you to create interface like:
```vue
<ais-panel>
<template slot="header">Hi</template>
<template slot="default" slot-scope="{ noRefinement }">
<p v-if="noRefinement">no results</p>
<ais-refinement-list attribute="brand" />
</template>
</ais-panel>
```
sandbox with this: https://codesandbox.io/s/znw7ry52wl (which now obviously doesn't work).
fixes #347
=> feat(panel): provide noRefinement scope to slots

package.json, src/components/VoiceSearch.vue, yarn.lock
**Summary**
This PR removes the default value of `searchAsYouSpeak` from component level.
When it's not given, the connector(`connectVoiceSearch`) recieves `undefined`, and the connector will use its own default value (which is `false`).
*Related discussion: [here](https://github.com/algolia/angular-instantsearch/pull/530#discussion_r286278985)*
=> fix(voiceSearch): remove default value of `searchAsYouSpeak` from component level

README.md, docs/layouts/common/header.pug, docs/src/advanced/integrate-with-nuxt.md, docs/src/getting-started/getting-started.md, docs/src/getting-started/installing.md.hbs, docs/src/stylesheets/components/_banner.sass
This makes the deprecation message on v1 more clear.
<details><summary> old design </summary> <img width="1207" alt="Screenshot 2019-06-25 at 12 50 12" src="https://user-images.githubusercontent.com/6270048/60092617-c7ad3400-9747-11e9-896a-79c0de6f11d8.png"> </details>
At the same time, this also makes sure all installation methods install `vue-instantsearch@1`
=> docs(v1): more visible deprecation

examples/ecommerce/src/App.vue, examples/ecommerce/src/widgets/NoResult.vue, examples/ecommerce/src/widgets/NoResults.vue
This adds the empty state when no hits are returned by the engine. It doesn't change the SFFV no results design.
related to: https://github.com/algolia/instantsearch.js/pull/3894
based on: https://github.com/algolia/react-instantsearch/pull/2601
If no filter are applied, the empty message asks the user to change the query. If there are filters applied, the empty message shows a different message and offers the user to clear the filters.
I added `removeWordsIfNoResults` to `allOptional` so that results are returned most of the time.
- [Preview with only query leading to empty results](https://deploy-preview-690--vue-instantsearch.netlify.com/examples/ecommerce/index.html?query=hellll)
- [Preview with filters leading to empty results](https://deploy-preview-690--vue-instantsearch.netlify.com …
=> chore(examples): add design for empty result at e-commerce demo

package.json, yarn.lock
This PR updates InstantSearch.js to [3.5.4](https://github.com/algolia/instantsearch.js/blob/develop/CHANGELOG.md#354-2019-07-01).
=> chore(deps): update InstantSearch.js to 3.5.4

CHANGELOG.md, package.json
This bumps InstantSearch to 3.5.4 to fix the highlighting bug
=> chore(release): v2.2.2

package.json, rollup.config.js, yarn.lock
I updated the rollup plugins responsible, and now dependencies for the frontend of InstantSearch are no longer included (preact, Hogan etc.)
Also enabled source maps for easier debugging of these issues in the future
=>  feat(umd): reduce size

src/components/RefinementList.vue, src/components/__tests__/RefinementList.js, src/components/__tests__/__snapshots__/RefinementList.js.snap
fixes #644
When we forward the class names from the refinement list itself, you can override the classes like this:
```vue
<template>
<ais-refinement-list
attribute="category"
searchable
:class-names="classNames"
/>
</template>
<script>
export default {
data() {
return {
classNames: {
'ais-RefinementList-list': 'refinement-list',
'ais-SearchBox-input': 'refinement-input',
},
};
},
};
</script>
```
=> feat(RefinementList): forward class names to input

src/mixins/widget.js
fixes #697
We are patching the InstantSearch instance in SSR, but you could be using the code for SSR without using the patched InstantSearch instance.
The error being thrown then is confusing, since it just complains about a missing property.
We have no differential error management with short & long error messages in prod/dev here yet, so I tried to be between both (not too long), this still has a .03kb difference in the bundle, so I updated the limits
=> fix(ssr): clearer error message when using ssr without the component

stories/RangeInput.stories.js
This PR adds `:lazy="true"` to a vue-slider story.
The option prevents from triggering too unnecessary queries while dragging.
=> chore: update vue-slider story

src/instantsearch.js
While using the `createWidgetMixin`, there is no easy way to reproduce all the DOM classes typically generated for widget components; the mixin used internally is not exposed for consumption in production environments.
Would like to be able to leverage the same pattern when wrapping additional template around existing components.
=> feat: Expose `createSuitMixin` for easy class reuse in custom components

package.json
This should allow people who are using Webpack, which doesn't correctly work with "non-fully-used" single files to still import only what's needed.
The size of tree-shaking vue-instantsearch isn't too different from the whole bundle, because the biggest parts are the InstantSearch class & the algoliasearch-helper. Luckily this will be better in the next major version.
see #725 (fixes part of it as it gives a workaround, but ideally it wouldn't be necessary)
=> feat(core): expose source files

.eslintrc.js, .storybook/styles.css, package.json, src/__tests__/index.js, src/components/ConfigureRelatedItems.js, src/components/__tests__/ConfigureRelatedItems.js, src/widgets.js, stories/ConfigureRelatedItems.stories.js, yarn.lock
This PR introduces a new experimental widget: `ais-experimental-configure-related-items`.
Combined with the `ais-hits` component, this widget allows to create related items experiences as seen in e-commerce and media use cases:
<details>
<summary>See more examples</summary>
</details>
- [Usage](https://github.com/algolia/vue-instantsearch/blob/dbc633f92a26ccc232a9cc66c89dfa3714e7f4f5/stories/ConfigureRelatedItems.stories.js)
- [Story](https://deploy-preview-751--vue-instantsearch.netlify.com/stories/?selectedKind=ais-configure-related-items&selectedStory=default&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)
The widget is render-less (it doesn't render anything), which means that no data is exposed to its scope.
- Slight bundle size increase
- …
=> feat(widgets): introduce `ConfigureRelatedItems` as experimental

examples/default-theme/package.json, examples/default-theme/yarn.lock, examples/e-commerce/package.json, examples/e-commerce/public/index.html, examples/e-commerce/yarn.lock, examples/media/package.json, examples/media/yarn.lock, examples/nuxt/package.json, examples/nuxt/yarn.lock, examples/ssr/package.json, examples/ssr/yarn.lock, package.json, yarn.lock
This change add support for algoliasearch v4 to Vue-InstantSearch.
No changes were necessary in the code. Also since the client is mocked in the unit tests we did not add an extra job on CIrcleCI to test with the 2 versions of the client.
The examples were updated to use the latest v4 beta.
**Important note**: we also upgraded the algoliasearch-helper dependency to 3.0.0 which is the version that support algoliasearch v4.
**Update**: after upgrading algoliasearch-helper from 2.26.1 ot 3.0.0 the bundle size jumped from 59KB to 68KB. We need to investigate on it:
<details>
<summary>Bundle size</summary>
Before:
```shell
┌────────────────────────────────────────────┐
│                                            │
│   Destination: dist/vue-instantsearch.js   │
│   Bundle Size:  241.07 KB …
```
=> feat(algoliasearch): add support for algoliasearch v4

package.json, yarn.lock
Before this `yarn build` failed due to the missing `EXPERIMENTAL_connectConfigureRelatedItems`.
=> chore(deps): update dependency instantsearch(v4.2.0) and algoliasearch-helper(3.1.0)

examples/nuxt/package.json, examples/nuxt/pages/search.vue, examples/ssr/package.json, examples/ssr/src/main.js, src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
this is done by making this dependency-injected to prevent the dependency being required for everyone
this is a breaking change, but I think I'll release it as 3.1.0 and will deprecate 3.0.0 & 3.0.1 as soon as this is merged and released Monday
=> fix(server): make vue-server-renderer not a dependency

package.json, yarn.lock
This PR updates the dependency instantsearch.js to v4.7.0.
=> chore(deps): update dependency instantsearch(v4.7.0)

src/components/ToggleRefinement.vue, stories/ToggleRefinement.stories.js
Hi :wave: 
This PR is for the proposal https://github.com/algolia/instantsearch.js/pull/4420, which allow multiple values for `on` and `off` props.
Thanks!
=> feat(widget:toggle-refinement): allow multiple values for "on" and "off"

src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
The check was on the widget itself, instead of on the current iteration. 
See this for original code which didn't have the issue:
https://github.com/algolia/instantsearch.js/blob/ada37ae054275d46cc2edaee0081562b6c35cbc8/src/widgets/index/index.ts#L101-L115
=> fix(ssr): allow getWidgetState to be empty for createURL

ship.config.js
This PR adds `ship.config.js` to add the team `instantsearch-for-websites` automatically as a reviewer for release PRs generated by Ship.js.
=> chore: assign the team automatically as release pr reviewers

src/components/InstantSearch.js, src/components/__tests__/InstantSearch.js
In the `routing` doc, we state:
> The object is accepted if it has either of these keys [...]
>
> — [Reference](https://www.algolia.com/doc/api-reference/widgets/instantsearch/vue/#widget-param-routing)
But we actually do warn when `router` or `stateMapping` is missing. This removes the warning in this case.
=> fix(routing): do not warn when `router` or `stateMapping` is missing

src/components/Highlighter.vue, src/components/__tests__/Highlight.js, src/util/parseAlgoliaHit.js
Vue by default removes nodes which are just whitespace: https://github.com/vuejs/vue/blob/ec78fc8b6d03e59da669be1adf4b4b5abf670a34/dist/vue.common.dev.js#L2527
We need to prevent this, since sometimes between highlights, there is just a space, we need to make the value not "wrapped". We can't make the value always "block" (i don't know the correct name for this), since that would add spaces between "inline" highlights.
fixes #826
=> fix(highlight): don't remove whitespace-only nodes

src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
The `scopedResults` object was missing when rendering the widget on server-side, crashing the widgets that were relying on it (like 
`AisCurrentRefinements` for example).
This PR fixes this by recalculating the scoped results and adding them to the render options (for this we're using the same method as in InstantSearch.js https://github.com/algolia/instantsearch.js/blob/68b20f487fcd54fd7dec11b4c494b6aa94a18516/src/widgets/index/index.ts#L154-L167)
Fixes #829
=> fix(ssr): fix missing scopedResults during render

src/components/RangeInput.vue
When calculating the range in `RangeInput.vue` the `min` and `max` values can fallback to `null`, which is not handled by the `connectRange` connector from `InstantSearch.js` (it expect either `undefined` or an empty string if the `min`/`max` value is not set).
See detailed report in https://github.com/algolia/vue-instantsearch/issues/833
This PR updates the fallback to `undefined` so the contract with `connectRange` is respected.
Fixes #833
=> fix(range-input): fix range input min and max values fallbacks

package.json, src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js, yarn.lock
in our guide for routing with vue router, you need to access the Vue Router instance. The most straightforward way for that is to move the construction of the server mixin into `data()`. `router` is useful for creating an instantsearch router compatible with vueRouter
=> feat(ssr): forward router instance to findResultsState clone

package.json, src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js, yarn.lock
Regardless of whether you _need_ to access it, it's commonly done for otherwise prerendered state. Since Vuex is a core plugin, we must support it like this
stacked PR on #863
=> feat(ssr): forward vuex instance to findResultsState clone

src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
propsData isn't valid as argument to `.extend`, but you don't need to call `new Vue(comp)`, it's the same as calling `new comp({propsData...})`
=> feat(ssr): forward propsData to recreated component

src/mixins/__tests__/panel.test.js, src/mixins/panel.js, stories/Panel.stories.js
you can see this when there's a query which is applied from the URL (sorry, not relevant in the storybook) which makes the `canRefine` (`ais-Panel--noRefinement`) different than the default (`true`)
=> fix(panel): react to changes on initial render

src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
The clone created in findResultsState also manually needs to forward slots, or the data won't be available.
=> fix(ssr): forward slots of the AisInstantSearchSsr component

package.json, src/components/InstantSearch.js, src/components/__tests__/InstantSearch-integration.js, src/util/createInstantSearchComponent.js, stories/RelevantSort.stories.js, yarn.lock
This PR adds `middlewares` prop to `<ais-instant-search>`.
<details>
<summary><i>ignore this. we're using `unuse` method.</i></summary>
Writing Vue code, users will expect `middlewares` prop to be reactive. Currently this PR handles newly added middlewares.
However, removed ones in the prop are not being handled at the moment.
1. In which case will people want to remove middlewares in the middle of their app's lifecycle?
2. We don't have an API to remove middleware from InstantSearch. We can manually call `middlewareToRemove.unsubscribe()`, but `instantSearchInstance` [still loops over](https://github.com/algolia/instantsearch.js/blob/master/src/lib/InstantSearch.ts#L580-L584) `this.middleware` to notify state changes, etc. So we need to have a proper API to support this reactive behavior …
=> feat(middlewares): add middlewares prop to ais-instant-search

package.json, src/components/HierarchicalMenu.vue, src/components/Hits.vue, src/components/InfiniteHits.vue, src/components/Menu.vue, src/components/MenuSelect.vue, src/components/NumericMenu.vue, src/components/RangeInput.vue, src/components/RatingMenu.vue, src/components/RefinementList.vue, src/components/ToggleRefinement.vue, src/components/__tests__/HierarchicalMenu.js, src/components/__tests__/Hits.js, src/components/__tests__/InfiniteHits.js, src/components/__tests__/Menu.js, src/components/__tests__/MenuSelect.js, src/components/__tests__/NumericMenu.js, src/components/__tests__/RangeInput.js, src/components/__tests__/RatingMenu.js, src/components/__tests__/RefinementList.js, src/components/__tests__/ToggleRefinement.js
This PR exposes `send-event` in the following widgets:
- HierarchicalMenu
- Hits
- InfiniteHits
- Menu
- MenuSelect
- NumericMenu
- RangeInput
- RatingMenu
- RefinementList
- ToggleRefinement
By supporting the `middlewares` API in the recent change, [the `insights` middleware works](https://codesandbox.io/s/throbbing-darkness-g7zpg?file=/src/App.vue) with Vue InstantSearch but with this PR, we can let users write custom components and still utilize `sendEvent` method.
=> feat(insights): expose `send-event` in widgets

package.json, src/mixins/panel.js, yarn.lock
Mitt is quite small, so doesn't have a big impact on bundlesize.
see https://v3.vuejs.org/guide/migration/events-api.html
This doesn't make it incompatible with Vue 2
=> feat(vue 3): prevent error by migrating events to mitt

src/components/Pagination.vue, src/components/SearchBox.vue, src/components/SearchInput.vue
v-model used to be @input / :value, but is now @update:modelValue / :modelValue. Since those don't overlap, it's possible to support both, by using them as fallback
"emits" is now also required in v3, so I added this to all components emitting
docs: https://v3.vuejs.org/guide/migration/v-model.html
=> feat(vue 3): compat for both versions of v-model

src/components/Highlighter.vue
In Vue 3 "functional" components no longer exist and are replaced with functions. Since Vue 2 has `Vue.default.version` and Vue 3 ahas `Vue.version`, this is how we can detect it, however I might move this to a function
docs: https://v3.vuejs.org/guide/migration/functional-components.html
=> feat(vue 3): make highlighter compatible

src/components/Configure.js, src/components/Index.js, src/components/InstantSearch.js, src/components/InstantSearchSsr.js, yarn.lock
createElement is no longer passed to the `render`, you need to import it statically. Unfortunately they didn't also add this export in v2 already
see: https://v3.vuejs.org/guide/migration/render-function-api.html
=> feat(vue 3): make render function of JS files compatible

src/util/createServerRootMixin.js
Since Vue 3, it seems `defineComponent()` should be used instead of `Vue.component()`.
I haven't got to testing the ssr, but at least this change unblocks the error with the default export.
related: https://v3.vuejs.org/api/global-api.html#definecomponent
=> feat(vue 3): support both defineComponent and component

src/mixins/widget.js
Vue 3 doesn't bind `this` when calling `default()` of a injected variable.
https://github.com/vuejs/vue-next/blob/540e26f49c09edf09b6a60ac2a978fdec52686bf/packages/runtime-core/src/apiInject.ts#L62-L64
=> feat(vue 3): support inject without `this`

package.json, src/mixins/panel.js, src/mixins/widget.js, src/util/createInstantSearchComponent.js
This PR renames `beforeDestroy` to `beforeUnmount` in case of Vue3 because it's been renamed.
https://v3.vuejs.org/guide/migration/introduction.html#other-minor-changes
=> feat(vue 3): rename beforeDestroy to beforeUnmount

rollup.config.js
This PR updates `external` property at the rollup config.
It adds `mitt` and `vue-demi`, and also updates it to be a function so that it can mark things like the following as external:
```
import indexWidget from 'instantsearch.js/es/widgets/index/index';
```
=> chore(vue 3): update `external` at rollup config

.eslintignore, src/components/SearchInput.vue, src/mixins/__tests__/panel.test.js
This PR fixes the failing unit tests for the panel widget.
It was testing with the internal (the event emitter), and got broken after we decided to use `mitt`. We should change the tests not to test with the internal, but for now, I'm just making it work.
(I'll deal with e2e tests later, too.)
=> fix(vue 3): fix unit tests for panel

src/components/Panel.vue
This PR fixes an issue to make Panel widget work in Vue 3.
(Even though it's in Vue 3, it tried to access $scopedSlots which doesn't exist any more.)
=> fix(vue 3): fix Panel

package.json, src/__tests__/index.js, src/components/DynamicWidgets.js, src/components/__tests__/DynamicWidgets.js, src/widgets.js, stories/DynamicWidgets.stories.js, yarn.lock
**Summary**
Adds a new widget _ais-experimental-dynamic-widgets_ that can be used to conditionally render other widgets. This condition is based on the search results, by default results.facetOrdering.facet.values, but can be overridden using transformItems
**Result**
```vue
<template>
<ais-experimental-dynamic-widgets :transform-items="transformItems">
<ais-refinement-list attribute="test1" />
<ais-menu attribute="test2" />
<ais-panel>
<ais-hierarchical-menu :attributes="hierarchicalAttributes" />
</ais-panel>
</ais-experimental-dynamic-widgets>
</template>
<script>
export default {
data() {
return {
hierarchicalAttributes: ["test3", "unused"],
};
},
methods(_attributes, { results }) {
// modified if you want to use userData instead of facet ordering
return results.userData[0].ordering; …
```
=>  feat(ais-dynamic-widgets): add implementation

src/components/Breadcrumb.vue, src/components/ClearRefinements.vue, src/components/CurrentRefinements.vue, src/components/HierarchicalMenu.vue, src/components/Highlighter.vue, src/components/Hits.vue, src/components/HitsPerPage.vue, src/components/InfiniteHits.vue, src/components/InstantSearch.js, src/components/Menu.vue, src/components/MenuSelect.vue, src/components/NumericMenu.vue, src/components/Pagination.vue, src/components/QueryRuleContext.js, src/components/QueryRuleCustomData.vue, src/components/RangeInput.vue, src/components/RatingMenu.vue, src/components/RefinementList.vue, src/components/SortBy.vue, src/components/ToggleRefinement.vue
for facetOrdering, we need to let InstantSearch.js decide the real default value of props. At the same time I removed all other defaults to avoid differences
=> feat(props): remove defaults

package.json, src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
This PR updates the implementation of `createServerRootMixin`.
It excludes the test cases for vue 3 about forwarding $root and $slots. I haven't figured it out, and if it's really necessary, etc.
I will try it out separately and if so, I'll probably do it in a separate PR as a fix (because I don't think I'll do it immediately).
---
It's normal that the CI doesn't pass here. It's fixed in https://github.com/algolia/vue-instantsearch/pull/1021 because
```
feat/vue3-compat
ㄴ test: update tests compatible for both vue 2 and vue 3 [1/2] #1014
ㄴ this PR
ㄴ  test: update tests compatible for both vue 2 and vue 3 [2/2] #1021
```
However once it's approved, I will rebase this and merge it as an individual commit to `feat/vue3-compat` (not mixing with the "update tests" PRs).
=> fix(vue 3): update the implementation of createServerRootMixin

.eslintignore, jest.setup.js, package.json, src/components/CurrentRefinements.vue, src/components/DynamicWidgets.js, src/components/SearchBox.vue, src/components/__tests__/Breadcrumb.js, src/components/__tests__/ClearRefinements.js, src/components/__tests__/CurrentRefinements.js, src/components/__tests__/DynamicWidgets.js, src/components/__tests__/HierarchicalMenu.js, src/components/__tests__/InfiniteHits.js, src/components/__tests__/InstantSearch-integration.js, src/components/__tests__/InstantSearchSsr.js, src/components/__tests__/Menu.js, src/components/__tests__/MenuSelect.js, src/components/__tests__/NumericMenu.js, src/components/__tests__/RangeInput.js, src/components/__tests__/RefinementList.js, src/components/__tests__/RelevantSort.js, src/components/__tests__/SearchBox.js, src/components/__tests__/StateResults.js, src/components/__tests__/VoiceSearch.js, src/components/__tests__/__snapshots__/Menu.js.snap, src/components/__tests__/__snapshots__/MenuSelect.js.snap, src/components/__tests__/__snapshots__/NumericMenu.js.snap, src/mixins/__tests__/panel.test.js, src/mixins/__tests__/widget.test.js, src/util/vue-compat/index-3.js, test/utils/index.js
This PR mainly updates all the incompatible test cases to work with both vue 2 and 3.
* We have no idea on when VTU is going to release the update. So I prefer replacing `vm.$set()` with `setData()` later in a separate PR.
* Another tasks I'm planning as separate PRs:
* `renderCompat` for InstantSearch, Configure, ... (covers createElement, h, and conditional props & attrs)
* shared util for `isVue3 ? this.$slots.default && this.$slots.default() : this.$slots.default`
* extracting as a script to add dependencies and run tests for vue 3
This PR is a stacked PR on https://github.com/algolia/vue-instantsearch/pull/1020, so it's easier to do them separately. Otherwise, we will apply them both in this branch and in the one for #1020.
=>  test: update tests compatible for both vue 2 and vue 3 [2/2]

package.json, src/components/Configure.js, src/components/DynamicWidgets.js, src/components/Index.js, src/components/InstantSearch.js, src/components/InstantSearchSsr.js, src/components/__tests__/Configure.js, src/components/__tests__/InstantSearchSsr.js, src/util/__tests__/createServerRootMixin.test.js, src/util/vue-compat/index-2.js, src/util/vue-compat/index-3.js, test/utils/index.js
This PR adds `renderCompat` and `getDefaultSlot` to support compatibility between the versions and to have less conditional codes.
=> refactor(vue 3): add utils for compatibility

.babelrc, package.json, src/util/vue-compat/index-2.js, yarn.lock
This fixes `renderToString` for vue 2 to get the `default` from the module and also adds `babel-plugin-dynamic-import-node` for jest.
=> fix(vue 3): fix renderToString for vue 2 and update babel config for jest

package.json, src/components/__tests__/CurrentRefinements.js, src/components/__tests__/HierarchicalMenu.js, src/components/__tests__/InstantSearch-integration.js, src/components/__tests__/RangeInput.js, yarn.lock
This PR updates `@vue/test-utils`
(https://github.com/vuejs/vue-test-utils-next/pull/767)
And updates some of the test cases to use `setData` which was impossible because VTU was wrongly concatenating arrays.
=> fix(vue 3): update @vue/test-utils and use setData for array items

src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
This PR removes the part where it was spreading the component to pass the propsData to the cloned component in Vue 3.
Theoretically we should pass the propsData from the original component to the newly cloned component, but I don't see the concrete real life example for that. Besides, the way we spread the component isn't ideal and we get warning messages from vue.
```
[Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.
```
If it turns out later to be a valid point with an example, we can discuss and address it.
=> fix(vue 3): do not pass props for cloned component in vue 3

.circleci/config.yml
This PR enables shipjs on `feat/vue3-compat` branch. By this change, we can create release pull-requests based on `feat/vue3-compat`.
When we merge the branch to `master`, I will revert this change, so that we can enable `shipjs trigger` only on `master` branch again.
=> chore(vue 3): enable shipjs

examples/vue3-ssr-vite/index.html, examples/vue3-ssr-vite/server.js, examples/vue3-ssr-vite/src/entry-server.js
Hello,
On SRR example with vite `render` function from `entry-server.js` return an array of 3 (html, algoliaStateScript and preloadLinks)
but on `server.js`, `render` is destructured with an array of 2 (html and preloadLinks)
It is better to pass an object to prevent argument shifting.
Now the example handle algoliaStateScript + preloadLinks with running for production !
=> Passing algoliaStateScript and preloadLinks from render

.babelrc, examples/nuxt/pages/search.vue, examples/ssr/src/main.js, examples/vue3-ssr-vite/src/main.js, examples/vue3-ssr-vue-cli/src/app.js, package.json, src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js, src/util/vue-compat/index-2.js, src/util/vue-compat/index-3.js, yarn.lock
This PR removes the code that dynamically importing `vue-server-renderer/basic` or `@vue/server-renderer` and now lets users pass `renderToString` function to `createServerRootMixin`.
Vue CLI and vite failed to run when those dependencies were not installed even though that importing code is never executed. Using `require` is not a good idea (especially in the ESM output). So we let users pass the function, although it's a breaking change.
=> fix(vue 3): let users pass renderToString to createServerRootMixin

src/components/RangeInput.vue
This PR removes the default min and max values from `ais-range-input`.
BREAKING CHANGE, but it won't likely affect the behavior.
=> fix(range-input): remove default min and max values from `ais-range-input`

package.json, yarn.lock
This PR updates the dependency instantsearch.js to 4.27.2 which recently fixed the type issue.
=> chore(deps): update instantsearch.js to 4.27.2

.eslintignore, .gitignore, CHANGELOG.md, examples/vue3-ssr-vite/src/main.js, examples/vue3-ssr-vite/src/pages/Home.vue, examples/vue3-ssr-vue-cli/src/app.js, examples/vue3-ssr-vue-cli/src/pages/Home.vue, package.json, rollup.config.js, scripts/build-vue2.sh, scripts/build-vue3.sh, src/components/RangeInput.vue
This PR shortens the import path for vue3
from
```js
import InstantSearch from 'vue-instantsearch/dist/vue3/es';
```
to
```js
import InstantSearch from 'vue-instantsearch/vue3/es';
```
=> chore(vue 3): shorten import path for vue3

src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
This PR fixes the regression from #1035.
Before #1035, we used to dynamically import `@vue/server-renderer` and called `renderToString()`, but it was only inside `search.findResultsState()`.
After #1035, importing `@vue/server-renderer` is on the user land, but it happens at `main.js` file where it exports `createApp` function.
And the error now happens because it is unnecessarily trying to import `@vue/server-renderer` on the browser and it's not meant to be (`main.js` is used in both client and server).
The solution here is to pass from entry-server.js `renderToString` to `createApp()` , because `serverPrefetch()` is called only on server, and entry-client.js not passing it won't make any issue.
This new API will help people (like me) not put server renderer in client bundle mistakenly, …
=> fix(vue 3): pass renderToString to findResultsState instead of createServerRootMixin

src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
Essentially the problem is that $vnode is usually available, but not when the this is a root Vue instance. In that case we are in the "Vue.component" case, which before now always was wrong (it takes two arguments, not one)
Same as #1104
see also #1054
=> fix(server): extend component correctly if at root

scripts/test-vue3.sh
As we manually install the versions, the latest version of transitive dependencies, which happens to be @babel/core@7.17.0, which has the bug https://github.com/babel/babel/issues/14233.
Really we should solve this problem completely different, maybe with a separate folder, a separate package.json/yarn.lock possibly, but I couldn't find a straightforward way to do that right now.
Test plan: ci for vue 3 is no longer failing
=> ci(vue3): pin lower version of @babel/core

src/util/__tests__/createServerRootMixin.test.js, src/util/createServerRootMixin.js
This is similar to how we forward $router and $store, but in this case it needs to happen before the beforeCreate of nuxt happens, as it uses that property
=> fix(nuxt3): forward $nuxt on the instance by default

package.json, src/util/__tests__/createServerRootMixin.test.js, yarn.lock
**Summary**
This PR updates the **instantsearch.js** dependency to allow the `<ais-hierarchical-menu>` widget to retrieve and display the full list of a refined item's parents values.
=> fix(ais-hierarchical-menu): show full hierarchical parent values

src/util/createServerRootMixin.js
This can't be tested afaict because we need `forceIsServerMixin` in the test.
discovered while debugging https://github.com/algolia/vue-instantsearch/issues/1125
=> fix(ssr): allow component without mixins to be extended

src/components/SearchBox.vue, src/components/SearchInput.vue, src/components/__tests__/SearchBox.js
JIRA: [FX-1552](https://algolia.atlassian.net/browse/FX-1552)
Fixes #1123 
This PR prevents state from overriding the query value in a search box if it still has focus. This can happen in a search-as-you-type environment when network speed is low and a user keeps on typing a query while requests are resolved.
=> fix(searchbox): prevent concurrent query updates from state while input is focused

src/components/SearchBox.vue, src/components/VoiceSearch.vue
fixes #1135
I've wen through the list of all widgets, and only these on VoiceSearch and queryHook on SearchBox were missing.
I didn't add any tests, as none of the widgets test widgetParams (since it's not tested in any other widget, and likely would just be a copy paste of the code)
=> fix(components): forward missing props in SearchBox and VoiceSearch

src/util/createServerRootMixin.js
In some nuxt 2 cases (https://github.com/algolia/vue-instantsearch/commit/acda29326475bd1b73f12b058a0c02df00b8b239#commitcomment-67430759) this.$nuxt is already defined by the framework, but not a setter, so we can't make it equal to the $nuxt of the component.
Luckily in Nuxt 2, setting $nuxt isn't crucial, and can thus be skipped.
=> fix(nuxt): only write $nuxt if it's writable

src/components/HierarchicalMenuList.vue, src/components/__tests__/__snapshots__/HierarchicalMenu.js.snap
**Summary**
This PR adds a new CSS class modifier for the `<ais-hierarchical-menu>` widget, following the addition made in the CSS specs.
| InstantSearch.css class name |
| --- |
| `.ais-HierarchicalMenu-link--selected` |
[FX-1795](https://algolia.atlassian.net/browse/FX-1795)
=> feat(ais-hierarchical-menu): add css class for link of selected menu item

package.json, src/__tests__/index.js, src/components/StateResults.vue, src/components/__tests__/StateResults.js, src/components/__tests__/__snapshots__/StateResults.js.snap, src/mixins/__mocks__/widget.js, yarn.lock
FX-1770
Note that this changes the implementation from connectStateResults to a render listener, as `loading` is otherwise inconsistently visible. This means it will no longer be counted in metadata.
Updated the helper in devDep to use ^ to avoid a duplicate with the InstantSearch.js version
=> feat(StateResults): give access to status and error

src/components/StateResults.vue, src/components/__tests__/StateResults.js, src/mixins/__mocks__/widget.js
fixes #1154
FX-1867
If there's results already available, we want to render them ASAP, not waiting for a render event, similar to how the error event is listened to "immediate"
=> fix(state-results): provide rendering variables for initial render
